<?php

	if (!class_exists('Timber')){
		add_action( 'admin_notices', function(){
			echo '<div class="error"><p>Timber not activated. Make sure you activate the plugin in <a href="' . admin_url('plugins.php#timber') . '">' . admin_url('plugins.php') . '</a></p></div>';
		});
		return;
	}

	class StarterSite extends TimberSite {

		function __construct(){
			add_theme_support('post-formats');
			add_theme_support('post-thumbnails');
			set_post_thumbnail_size( 1920, 600, true ); 
			add_image_size('home_thumb', 420, 372, true);
			add_image_size('about_thumb', 420, 220, true);
	    add_image_size('shows_thumb', 620, 349, true);
			add_image_size('show_main_thumb', 940, 460, false);
			add_theme_support('menus');
			add_filter('timber_context', array($this, 'add_to_context'));
			add_filter('get_twig', array($this, 'add_to_twig'));
			add_action('init', array($this, 'register_post_types'));
			add_action('init', array($this, 'register_taxonomies'));
			add_action('wp_enqueue_scripts', array($this, 'register_scripts'));
			parent::__construct();
		}

		function register_scripts(){
			wp_enqueue_script('template', get_template_directory_uri() . '/theme/compressed/template.min.js', array( 'jquery' ), '1.0.0', true);
		}

		function register_post_types(){
			//this is where you can register custom post types
			$labelsShow = array(
		    'name' => 'Shows',
		    'singular_name' => 'Show',
		    'add_new' => 'Novo Show',
		    'add_new_item' => 'Adicionar novo Show',
		    'edit_item' => 'Editar Show',
		    'new_item' => 'Novo Show',
		    'view_item' => 'Ver Show',
		    'search_items' => 'Procurar Show',
		    'not_found' =>  'Não foram encontrados Shows',
		    'not_found_in_trash' => 'Não há Shows no lixo', 
		    'parent_item_colon' => '',
		    'menu_name' => 'Shows'

		  );
		  $argsShow = array(
		    'labels' => $labelsShow,
		    'public' => true,
		    'publicly_queryable' => true,
		    'show_ui' => true,
		    'exclude_from_search' => false,
		    'show_in_menu' => true,
		    'query_var' => true,
		    'rewrite' => true,
		    'capability_type' => 'post',
		    'has_archive' => true,
		    'hierarchical' => false,
		    'menu_position' => 5,
		    'supports' => array('title', 'editor', 'excerpt', 'thumbnail')
		  );
		  register_post_type('show',$argsShow);
		}

		function register_taxonomies(){
			//this is where you can register custom taxonomies
		}

		function add_to_context($context){
			// $context['foo'] = 'bar';
			// $context['stuff'] = 'I am a value set in your functions.php file';
			// $context['notes'] = 'These values are available everytime you call Timber::get_context();';
			$context['bands'] = array("1° ATO - CIA DE DANÇA", "A HISTÓRIA DE NÓS DOIS (peça teatral)", "A HACK AND A HACKAW", "ABORTED", "ABRAMOVICH/FERRE", "DUO", "ABSU ACHERON", "A CORDA - DUO", "ADRIANA CALCANHOTO", "ADRIANA DEFFENTI & ARTHUR DE FARIA", "ADRIANA MACIEL", "ADRIANA MIKI", "AFFONSINHO", "AFROSAMBAJAZZ", "ALCEU VALENÇA", "ALEXANDRE STAROSTA & DAVI MOREIRA", "ALAÍDE COSTA", "ALCIONE", "DIOGONOGUEIRA", "MARTINHO DA VILA E ROBERTÁ SÁ – NÍVEA VIVA O SAMBA", "ALEGRE CORRÊA E WOLFGANG MUTHSPIEL", "ALESSANDRA LEÃO", "ALESSIO NEBIOLO", "ALEXANDRA LUBCHANSKY", "ALEXANDRA SCOTTI", "ALEXANDRE DOSSIN", "ALEYSON SCOPEL", "ALINE CALIXTO", "AMARANTO", "AMELITA BALTAR", "AMÉRICA", "AMANCIO PRADA", "ANA MARTINS", "ANABEL MONTESINOS", "ANDRÉ CHRISTÓVAN", "ANDRÉIA DIAS", "ÂNGELA DIEL", "ÂNGELA RO RO", "ATHÉSIA & GENTLEMAN", "ANTONIO MARQUEZ CIA", "ANTONIO MENEZES", "ANTÔNIO NÓBREGA", "ARI BORGER", "ARIEL ARDIT", "ARMANDINHO (BA)", "ARMANDINHO (RS)", "ARNALDO ANTUNES", "ARNALDO COHEN", "ARRIGO BARNABÉ", "ARTE EN PARTE DUO", "ARTHUR DE FARIA", "ARTILLERY", "ARTO LINDSAY", "ARY TOLEDO", "ASQ CIA DE DANÇA", "ASTRONAUTA PINGUIM", "AYRES POTTHOFF & FELIPE AZEVED0", "BABI MENDES", "BADI ASSAD", "BALLET NACIONAL DE CUBA", "BALLET IMPERIAL DA RUSSIA", "BALLET JAZZ DE MONTREAL", "BALLET TEATRO GUAÍRA", "BARROCKÓFILO ", "BATUQUE DE CORDAS", "BEATLES'N'CHORO", "BEATS - THE BELPHEGOR", "BEHEMOTH", "BENJAMIM TAUBKIN", "BENJAMIN SUNG", "B. B. KING", "BEBEL GILBERTO", "BEBETO ALVES", "BELCHIOR", "BEN PORTSMOUTH AND TCE BAND", "BENJAMIN HERMANN KWARTET B.J. THOMAS", "BOB BROZMAN", "BOCA LIVRE", "BONNIE PRINCE BILLY", "BOSSACUCANOVA", "BOSSA ENTRE AMIGOS", "BLUES ETÍLICOS", "BRAD MEHLDAU", "BRASSUKA", "BRIAN CHAMBOULEYRON", "BRUCE EWAN", "BUDAPEST STRINGS - THE", "BUDDY GUY", "CAETANO VELOSO", "CAMBADA MINEIRA", "CANNIBAL CORPSE", "CARIOCAS - OS", "CARLOS BARBOSA LIMA", "CARLOS CAREQA", "CARLOS CASACUBERTA", "CARLOS LYRA", "CARLOS NAVAS", "CARMELO DE LOS SANTOS", "CÁSSIA ELLER", "CAT POWER", "CÁTIA DE FRANÇA", "CELIA", "CELTIC LEGENDS", "CELSO BLUES BOY", "CENA 11 CIA DE DANÇA", "CEUMAR", "CEUMAR & DANTE OZZETTI", "CHAMBINHO DO ACORDEON", "CHE BOTIJA", "CHEVELLES. THE", "CHICAGO BRASS QUINTET", "CHICAS - AS", "CHICO CÉSAR", "CHICK COREA", "CHORAMUNDO", "CHORONAS", "CIA FILARMÔNICA DE SÃO PAULO", "CIA BARBIXAS DE HUMOR", "CIDA MOREIRA", "CIDADE NEGRA", "CLARA BECKER", "CLARA AVERBUCK & THE ONEYDCATS", "CLARICE FALCÃO", "CLAUDETE SOARES", "CLAUDIA TELLES", "CLAUDIA TOMÁZ", "CLÁUDIO DAUELSBERGER ", "CLAUDIO LEVITAN E VANDERLEI FALKENBERG", "CLAUDIO NUCCI", "COLLEEN", "COME TOGETHER PROJECT", "COMMITMENTS - THE", "CONFRARIA DO SAX", "CONJUNTO DE CÂMARA DE PORTO ALEGRE", "CONNOR ORBEST AND THE MYSTIC VALLEY BAND", "CONSUELO DE PAULA", "CORAL DA UFRGS", "CORDEL DO FOGO ENCANTADO", "CRISTIANO HANSEN & CAIO MARTINEZ", "CRISTINA BANEGAS", "CRISTINA BRAGA", "CRISTINA BUARQUE", "CRISTINA ORTIZ ", "CRISTOVÃO BASTOS", "CUARTETO QUIROGA ", "CURUPIRA - TRIO", "2i2 QUARTET", "DADO VILLA LOBOS", "DADO VILLA LOBOS - JOÃO BARONE - TONI PLATÃO E LEONI CANTAM BEATLES", "DAMS LASER VAMPIRES", "DANIEL DREXLER", "DANIEL WOLFF", "DANIELE ALBERTI", "DANNI CARLOS", "DANILO CAYMMY", "DANNY VINCENT", "DARKO BRLEK", "DAVE HOLLAND QUINTET", "DEAD KENNEDYS", "DEAD FISH", "DEBORAH COLKER - CIA", "DEDO DE MOÇA", "DELICATESSEN", "DEMÔNIOS DA GAROA", "DENISE REIS", "DÉO RIAN", "DESTROYER 666", "DESTRUCTION", "DINO RANGEL", "DIEGO MAX GILES", "DISCOCUECAS", "DISMEMBER", "DJ HUM", "DJ DOLORES", "DJAVAN", "DOCE DE COCO - REGIONAL", "DOG EAT DOG", "DOM LA NENA", "DOMINGOS DE OLIVEIRA", "DÓRIS MONTEIRO", "DOUBLE TROUBLE ", "DR. QUEEN", "DR. SIN", "DUDA GUEDES", "DULCE QUENTAL", "DUO A CORDA", "DUO ASSAD", "DUO ACOSTA & ALVAREZ", "DUO CALAVENTO", "DUO FAIN-MANTEGA", "DUO GISBRANCO", "DUO IMINA", "DUOFEL", "DUO SNAJER WINDFELDT", "DYING FETUS", "ED MOTTA", "EDNARDO", "EDUARDO CASTAÑERA", "EDUARDO DUSSEK ", "EDUARDO EGUEZ", "EDUARDO KREMER", "EDU LOBO", "EDU MARTINS GRUPO", "EDUARDO SANTHANA & LAÉRCIO DE FREITAS", "EDVALDO SANTANA", "EL ARRANQUE", "ELIANA PRINTZ", "ELISA LUCINDA", "ELIZAH", "ELZA SOARES", "ELTON MEDEIROS", "EL VIEJO ALMACÉN", "EMMERSON NOGUEIRA", "ENÉIAS XAVIER QUARTETO", "ENGENHEIROS DO HAWAII", "ENTHRONED", "ENTREQUATRE", "ERASMO CARLOS", "ERIC BURDON", "ERIKA MACHADO", "EVA FAMPAS", "EVENS - THE", "EVELINE HECKER", "EXODUS", "EXHUMED", "EXUMER", "FABIANA COZZA", "FÁBIO CALAZANS & GRUPO", "FABRÍCIO FORTES", "FADO AO CENTRO", "FAMILIA LIMA", "FÁTIMA GUEDES", "FAUST QUARTETT", "FELIPE AZEVEDO E OLIVIER FOREL", "FERNANDO CABRERA", "FERNANDO ESPÍ", "FERNANDO NORONHA ", "FERNANDO SODRÉ", "FERRE & ABRAMOVICH - DUO", "FINAL FANTASY (OWEN PALLET)", "FINALLY DOOMSDAY", "FITO PAEZ", "FLAVIO ADONIS", "FLÁVIO GUIMARÃES", "FLAVIO SALA", "FÓRUM ECONÔMICO MUNDIAL - DAVOS / SUIÇA 2012 (artistas brasileiros)", "FRANCIS HIME", "FRANCIS HIME & OLIVIA HIME", "FRANÇOIS VIROT", "FRANK SOLARI", "FRANK JORGE", "FRED MARTINS", "FREDDY COLE", "GAL COSTA", "GAMES CLASSIC SHOW", "GANGAJANG", "GAROTOS PODRES", "GAVRIEL LIPKIND", "GEMINIS BEE GEES", "GERALDO AZEVEDO", "GERALDO FLACH & CELAU MOREIRA", "GERALDO FLACH", "GERALDO VIANNA", "GILBERTO GIL", "GILSON PERANZETTA ", "GIVERNY - TRIO", "GLAUCIA NASSER", "GLÓRIA IRIART", "GUISEPPE ANDALORO", "GOLD CHAINS", "GONZALO RUBALCABA ", "GORGOROTH", "GOV’T MULE ", "GREG WILSON", "GUILHERME ARANTES", "GUILHERME GRANADO", "GUILLHERMO ZARBA", "GUILLO ESPEL - CUARTETO", "GUINGA ", "GUIZADO", "HARD WORKING BAND ", "HATE", "HELDER VASCONCELOS", "HÉLIO DELMIRO", "HÉLIO ZISKIND", "HELLO SAFERIDE", "HENRIQUE CAZES ", "HENRY GRAY", "HENRY LENTINO ", "HERMETO PASCHOAL", "HEXA E NANDO BARTH", "HIGH ESCOLA MUSICAL", "HIGH PLACES ", "HOLIDAY ON ICE", "HONEYBOY EDWARDS ", "I BRICCONCELLO", "IGNAZIO BALLATO ", "IMMOLATION", "INCANTATION", "INEZITA BARROSO", "IZABEL PADOVANI & RONALDO SAGGIORATO ", "IVONE PACHECO", "JACARANDÁ - GRUPO", "JACK BRUCE", "JAIR OLIVEIRA", "JAMES COTTON", "JAMES REYNE", "JAMES WHEELER", "JANICE STUMPF ", "JACQUELINE THIESSEN", "JARDS MACALÉ ", "JARI TERRES", "JAZZ 6", "JEFF GARDNER", "JEFF HEALEY", "JEFF SCOTT SOTO & TEMPESTT", "JENS LEKMAN", "JERZY MILEWSKI", "JOANA", "JOANNA NEWSON", "JOÃO BOSCO", "JOÃO DONATO", "JOÃO GILBERTO ", "JOE HENDERSON", "JOE LYNN TURNER", "JOHNNY ALF", "JOHN HAMMOND ", "JOHN MAYALL", "JOHN PIZZARELLI ", "JOHN PRIMER", "JOHN SCOFIELD TRIO & THE SCOHORNS", "JOHN T. LA BARBERA", "JOHNNY RIVERS", "JON ANDERSON", "JORGE DREXLER ", "JORGE MAUTNER", "JORGE VERCILLO", "JOSEE KONING", "JOSÉ GONZALEZ", "JOSÉ MANUEL LEON", "JOTA QUEST", "JOVINO SANTOS NETO", "JOYCE ", "JUAN FALU", "JUANA MOLINA", "JULIO PANE", "JULIO RENY ", "JURANDIR SANTANA & GRUPO", "JUSSARA SILVEIRA & LUIZ BRASIL", "JUSTINE", "KAT PARRA", "KÁTIA B", "KEEP OF KALESSIN", "KOH GABRIEL KAMEDA", "KEVIN JOHANSEN ", "KIKO LOUREIRO", "KRISIUN", "LA CHICANA", "LAETITIA SADIER", "LANNY GORDIN", "LARRY CORYELL ", "LARRY McCRAY", "LA TABARÉ ", "LAURA FINOCCHIARO", "LAURA DE SOUZA E ORQUESTRA UNISINOS", "LAURIE ANDERSON", "LEANDRO BRAGA ", "LEILA PINHEIRO");
			$context['bands2'] = array("LENINE", "LEO MINAX", "LEMONHEADS", "LIL ' RAY NEAL", "LILIANA HERRERO", "LIRA D'ORFEU", "LISA LI-LUNDI", "LISE + BARULHISTA", "LIZ HAMILL", "LÔ BORGES", "L.O.M. TRIO", "LONI SEIVA", "LOOP B", "LOS SWING TIMERS", "LOURDES RODRIGUES", "LUCAS AVELAR", "LUCAS VOLPATTO", "LUCHO GATICA", "LUCIANA RABELLO", "LUCIANO BRUNO", "LUCIANO MAIA", "LUCINA", "LUCINHA LINS", "LUCIO YANEL", "LUIZ CARLOS BORGES", "LUIZ MELODIA", "LUIZ TATIT", "LULU SANTOS", "LYNWOOD SLIM", "MACFECK", "MADCAT", "MAFALDA MINNOZZI", "MAGIC SLIM", "MAÍRA FREITAS", "MALEVOLENT CREATION", "MALY WEISEMBLUM", "MAMMA MIA ABBA LIVE", "MAN OR ASTROMAN", "MARCEL POWELL", "MARCELO DELACROIX E SIMONE", "RASSLAN", "MÁRCIO MONTARROYOS", "MARCOS NIMRICHTER & CAIO", "MÁRCIO", "MARCOS SACRAMENTO", "MARCOS E KARINA SOUZA", "MARDUK", "MARIA ALCINA", "MARIA AVENA", "MARIA BETHÂNIA", "MARIA BETHÂNIA & OMARA PORTUONDO", "MARIA LUCIA", "MÁRIO FALCÃO", "MARIO SÉVE & MARCLEO FAGERLANDE", "MARK MULLEY", "MARK RAMONE AND INTRUDERS", "MARKU RIBAS", "MARIA GADU", "MARTIN BUSCAGLIA", "MARTIN TURNER’S WISHBONE ASH", "MASSIMO MERCELLI", "MASTER", "MAURÍCIO PEREIRA", "MAURO SENISE", "MAX DE CASTRO", "MEDIALUNAS", "MEIRELLES E OS COPA 5", "MEN AT WORK", "MEMPHIS LA BLUSERA", "MENINOS CANTORES DE SAN FLORIAN ", "MENINOS CANTORES DE VIENA", "MERCADORIAS E FUTURO, peça", "MERCEDES SOSA", "MICHAEL DOTSON", "MIDORI", "MIGUEL PROENÇA", "MIGUEL TRÁPAGA", "MIKE DEL FERRO TRIO", "MIKE STERN", "MILLENCOLIN", "MINI MANUAL DE QUALIDADE DE VIDA (peça teatral)", "MIRIAN MARIA", "MILTINHO", "MIÚCHA E GALO PRETO", "MODERNA TRADIÇÃO", "MONARCO", "MONOAURAL", "MÔNICA SALMASO", "MÔNICA SALMASO E PAU BRASIL", "MÔNICA TOMASI", "MORAES MOREIRA", "MORENO + 2", "MORRIS ALBERT", "MOSCOW CIRCUS ON ICE", "MOZART MELLO", "MUDHONEY", "MULHERES NEGRAS, OS", "MUSICANDO", "MUTANTES, OS", "MXPX", "NAÇÃO ZUMBI", "NANA MOUSKOURI", "NANÁ VASCONCELOS", "NÁ OZZETTI", "NATHAN BELL", "NAZARETH", "NAZARETH ILUMINADO", "NASI E OS IRMÃOS DO BLUES", "NEI LISBOA", "NEI LISBOA & VITOR RAMIL", "NEI LOPES", "NELSON COELHO DE CASTRO", "NELSON COELHO DE CASTRO & GELSON OLIVEIRA", "NELSON FREIRE", "NELSON FREIRE & MARTA ARGERICH", "NELSON SARGENTO", "NENÊ (CAPOEIRA)", "NENÊ TRIO", "NENHUM DE NÓS", "NENUNG, 4NAZZO E BIBA MEIRA", "NETO FAGUNDES", "NEW E CONFRARIA DO SAX", "NEW ENGLAND CONSERVATORY", "OBITUARY", "PHIL MINTON & SPEEQ", "PHILARMONIC ORCHERTRA", "PRIMEIRO AS DAMAS", "NEY MATOGROSSO", "NICOLAS KRASSIK", "NINA WIRTTI", "NÓ EM PINGO D'ÁGUA", "NOSSO TRIO", "NOFX", "NUNO MINDELIS", "O MELHOR MELHOR SHOW DO MUNDO (peça teatral)", "O MÚSICO E O MÁGICO", "OBITUARY", "ODAIR JOSÉ", "OLEG FATEEV & SIMONE SOUL", "OLINDA ALLESSANDRINI", "OLIVIA BYINGTON", "OLY JR.", "OMAR GIAMMARCO", "ORQUESTRA SESI FUNDARTE", "ORQUESTRA SINFÔNICA DE PORTO ALEGRE - OSPA", "ORQUESTRA SINFÔNICA DO ESTADO DE SÃO PAULO - OSESP", "OS OSTRAS", "OSWALDO MONTENEGRO", "OSCAR DOS REIS", "O RODA", "OS THE DARMA LÓVERS", "8VB", "OWEN PALLET, FINAL FANTASY", "PABLO ARRIETA", "PACO DE LUCIA", "PALAVRA CANTADA", "PATO BANTON", "PATO FU", "PATRICIA MARX", "PATTY ASCHER", "PAU BRASIL", "PAULA SANTORO", "PAULINHO BOCA DE CANTOR", "PAULINHO DA VIOLA", "PAULINHO MOSKA", "PAULINHO TAPAJÓS", "PAULO BELINATTI", "PAULO MOURA & YAMANDÚ COSTA", "PEDRO LUIZ E A PAREDE", "PEDRO VERÍSSIMO & IZMÁLIA", "PEKKA PYLKKÄNNEN & TUBE FACORY", "PEREIRA DA VIOLA", "PÉRICLES CAVALCANTI", "PERY RIBEIRO", "PETER CETERA", "PHIL GUY", "PHIL MINTON & SPEEQ", "PHILIPPE POWELL", "PIERRE HOMMAGE", "PLATTERS, THE", "POETS, OS", "PROYECTO ANÁBASIS", "PRIMEIRO AS DAMAS (peça teatral)", "PULLEY", "QUATORZE BIS", "QUARTETO AZURE", "QUARTETO BESSLER", "QUARTETO HUGO WOLF", "QUARTETO MAOGANI", "QUARTETO PORTO ALEGRE", "QUASAR CIA DE DANÇA", "QUINTETO ANTARES", "QUINTETO LA CAMORRA", "QUINTETO PERSCH", "RAFAEL ALTINO", "RAUL ELLWANGER", "RAUL DE SOUZA", "RAVI", "RAVI COLTRANE", "REBECA MATTA", "RECITATOS", "REFREE", "RENATA ARRUDA", "RENATO BORGHETTI", "RENATO PEREIRA", "RENATO RUSSO, A PEÇA", "RICK ESTRIN", "RITA RIBEIRO", "R. J. MISCHO", "ROBERTA SÁ", "ROBERTO CORREA", "ROBERTO MENESCAL", "ROBERTO MENESCAL E ANDY SUMMERS", "RODRIGO ALQUATI", "RODRIGO SÁ", "RODRIGO SILVEIRA", "RODRIGO GARCIA LOPES", "ROGÉRIO CAETANO & LUIS BARCELOS", "ROMAN ZASLAWSKI", "RÔMULO FRÓES", "RONNIE EARL", "ROSA PASSOS", "ROSEANNA VITRO", "ROUPA NOVA", "SADUS", "SANDY", "SASKIA LAROO", "SASSARICANDO", "SAVOY BROWN", "SCHNEIDER TM", "SEBASTIÃO TAPAJÓS E MAURICIO EINHORN", "SÉRGIO SANTOS", "SEVERE TORTURE", "SHELLAC", "SIBA", "SILVERIO PONTES E ZÉ DA VELHA", "SIMONE ", "SÓCIO", "SODOM", "SOLUS, QUINTETO DE METAIS", "SOLON FISHBONE", "SPY VS. SPY", "ST. PETERSBURG BALLET", "STEINAR RAKNES QUARTET", "STEREO TOTAL", "SUÍTE PARA FLAUTA E JAZZ PIANO", "SURURU NA RODA", "SURICA E NILZE CARVALHO", "TACO PUNTA Y TRASPIÉ", "TANGHETTO", "TANGO XXI, CIA/TANGO A TIERRA", "TANKARD", "TEATRO NEGRO DE PRAGA", "TEN YEARS AFTER", "TEQUILA BABY", "TERESA CRISTINA & GRUPO SEMENTE", "TETÊ ESPINDOLA", "TETECO O REI DO RISO", "THALMA DE FREITAS", "THEDDY CORRÊA & LUIZ MARENCO", "THIAGO COLOMBO", "THIAGO DELEGADO", "THIAGO PETIT", "TIAGO IORC", "TIAS DO SAMBA", "TITA PARRA", "TITO MADI", "TOM CAVALCANTE", "TOM ZÉ", "TONDA Y SU COMBO", "TONHO CROCCO E PAU BRASIL", "TOQUINHO", "TOQUINHO E JOÃO BOSCO", "TOQUINHO E MPB4", "TOTI SOLER", "TOTONHO VILLEROY", "TREVOR WATTS", "TRIBUTO A CHET BAKER (DANIEL SZAFRAN E CLAUDIO FARIA)", "TRIO DIEL, BALBINDER E CORDELA", "TRIO DE MADEIRAS DE PORTO ALEGRE", "TRIO MADEIRA BRASIL", "TRIO KAISER MILLER BOCK", "TUNAOI", "UAKTI", "UFO", "ULISSES ROCHA", "UMA NOITE NA LUA (peça teatral)", "UTE LEMPER", "VADER", "VALDIR VERONA", "VANESSA BUGMAGNY", "VANESSA DA MATTA", "VÂNIA BASTOS", "VELHA GUARDA DA MANGUEIRA", "VELHA GUARDA DA PORTELA", "VERÔNICA FERRIANI", "VICTOR BIGLIONE", "VIRGINIA RODRIGUES", "VITAL REMAINS", "VITOR RAMIL", "VITOR RAMIL & PAULINHO MOSKA", "VLADIMIR VACLAVEK AND THEATRE ROYAL", "VOCAL 5", "WAGNER TISO", "VALDIR VERONA", "WALTER ALFAIATE", "WALTER FRANCO", "WANDER LEE", "WANDI DORATIOTTO", "WAR-HED", "WAYNE HUSSEY", "WENDY MCNEILL", "WENYU SHEN", "WHO’S BAD", "WILL VINSON", "WILLY GONZÁLEZ", "WITHOUT WORDS", "WOODY MANN", "YAMANDÚ COSTA", "YOHTU YINDI", "XANGAI", "YUSA", "ZECA BALEIRO", "ZECA BALEIRO & ZELIA DUNCAN", "ZÉLIA DUNCAN", "ZÉ DA VELHA & SILVÉRIO PONTES", "ZÉ GOMES", "ZÉ MENEZES", "ZÉ NOGUEIRA", "ZÉ RODRIX", "ZOSO");
			$context['search'] = $_GET['s'];
			$context['menu'] = new TimberMenu();
			$context['site'] = $this;
			return $context;
		}

		function add_to_twig($twig){
			/* this is where you can add your own fuctions to twig */
			$twig->addExtension(new Twig_Extension_StringLoader());
			// $twig->addFilter('get_permalink_by_name', new Twig_Filter_Function('get_permalink_by_name'));
			return $twig;
		}

	}

	new StarterSite();

	function get_permalink_by_name($page_name)
	{
	  global $post;
	  global $wpdb;
	  $pageid_name = $wpdb->get_var("SELECT ID FROM $wpdb->posts WHERE post_name = '".$page_name."'");
	  return get_permalink($pageid_name);
	}
	/*function myfoo($text){
    	$text .= ' bar!';
    	return $text;
	}*/